# PostgreSQL Phase 1
pg.host=postgres
pg.port=5432
pg.db=datapipeline
pg.user=Projet_MVP2025
pg.password=Ynov2025

# SQL d'extraction (depuis chart_snapshots + genres + tracks + artists)
sql.query=SELECT cs.ref_genre_id AS genre_id, g.name AS genre_name, cs.track_id, t.title, a.name AS artist_name, cs.position AS rank \
FROM chart_snapshots cs \
LEFT JOIN genres g ON cs.ref_genre_id = g.genre_id \
LEFT JOIN tracks t ON cs.track_id = t.track_id \
LEFT JOIN artists a ON t.artist_id = a.artist_id \
ORDER BY cs.snapshot_time DESC

# Limite de lignes (optionnel)
limit.rows=5000

# Chemins HDFS pour Phase 2
hdfs.input.path=/data/phase2/input/genre_tracks.tsv
hdfs.output.path=/data/phase2/output/genre_top_tracks
